### ISSUE TITLE
Add some resources for learning about transactions

### ISSUE THREAD

**Issue by nrc** [tikv/sig-transaction#3]
Some ideas:

* introductory documentation
* collect links to blog posts and tutorials
* collect papers

**Comment by youjiali1995** [comment]
Is it necessary to write detailed and up-to-dated documents? I think all posts are general now.

**Comment by nrc** [comment]
I think detailed docs should be with code. We can link old and new posts and state what is true and what is out of date. We should avoid having too many docs in this repo, and prefer to link to docs on the blog, in code, etc. IMO we should have some very basic introductory material here so people can get started.

**Comment by srisatya1197** [comment]
Is anyone working on this issue?

**Comment by nrc** [comment]
> Is anyone working on this issue?

Not that I know of, please feel free to work on something. If you need any pointers for where to get started, let me know.

**Comment by srisatya1197** [comment]
I would like to work on this issue. I need help as well if I'm assigned.

**Comment by srisatya1197** [comment]
@nrc Sir Is there any discord/slack channel for help.

**Comment by andylokandy** [comment]
> I would like to work on this issue. I need help if I'm assigned.

Thanks for your reply. Before assigning the issue to you, may I ask whether or not you have already some resources for putting into the sig. If so, could you please share the link to those resources?

By the way, just comment on this issue for help.

**Comment by srisatya1197** [comment]
@andylokandy Sorry I didn't understand which resources you are referring?

**Comment by srisatya1197** [comment]
Is this link suitable resource @andylokandy :
https://www.ibm.com/cloud/blog/database-deep-dives-pingcap-and-tikv

**Comment by tisonkun** [comment]
@srisatya1197 thanks for your interests. I can see the document you link is useful but it seems unsatisfied the whole idea of this issue. Since this issue has a bigger image all of 

> introductory documentation
> collect links to blog posts and tutorials
> collect papers

However, the knowledge you brought is useful and you can just create a pull request referred to this issue as part of its work. If you get assign on this issue, it might be a long term effort to collect / write resources for learning about transaction. At least we reach a consensus on "enough resources".

I highly recommend you just create a pull request referred to this issue as part of its work.

**Comment by srisatya1197** [comment]
Ok will do it. But, it's not assigned.  Yes I know it's not as satisfactory as other blogs .

**Comment by srisatya1197** [comment]
Should I write a blog?

**Comment by tisonkun** [comment]
> Ok will do it. But, it's not assigned. Yes I know it's not as satisfactory as other blogs .

I think it is viable assign this issue to you so you can go ahead if it is your concern. However, this issue remains until reach a consensus on "enough resources" and if there is someone else want to contribute, it is also welcome despite this issue is assigned.

> Should I write a blog?

What "blog" do you mean? In my understanding you can just create a pull request adding new files under [this directory](https://github.com/tikv/sig-transaction/tree/master/doc/tikv)

**Comment by srisatya1197** [comment]
Ok Sir.

**Comment by srisatya1197** [comment]
@andylokandy I have a doubt should I add the link which I have shared before or what?

**Comment by andylokandy** [comment]
I think that blob is not that useful for *learning transaction*?

**Comment by tisonkun** [comment]
@srisatya1197 you can just attach the link to resource you'd like to add here or create a pull request against doc/tikv, organize your content properly.

**Comment by srisatya1197** [comment]
@andylokandy @tisonkun https://dev.to/srisatya/for-readers-that-may-not-be-familiar-what-are-tidb-and-tikv-3m56
can you please check this link.
